;  CD-Rom Data/Overlay reference labels
;  Generated by pyDiscMaker Version 1.12
; (C) 2019 The DiscMaker Project

_ADDR_ipl = 0
_SIZE_ipl = 4096
_SECSIZE_ipl = 2

_ADDR_Main_Program = 2
_SIZE_Main_Program = 16384
_SECSIZE_Main_Program = 8

_ADDR_level1 = 10
_SIZE_level1 = 16384
_SECSIZE_level1 = 8

_ADDR__CDROM_Specs_Padding = 18
_SIZE__CDROM_Specs_Padding = 270336
_SECSIZE__CDROM_Specs_Padding = 132

