;  CD-Rom Data/Overlay reference labels
;  Generated by pyDiscMaker Version 1.12
; (C) 2019 The DiscMaker Project

_ADDR_ipl = 0
_SIZE_ipl = 4096
_SECSIZE_ipl = 2

_ADDR_Main_Program = 2
_SIZE_Main_Program = 24576
_SECSIZE_Main_Program = 12

_ADDR_art = 14
_SIZE_art = 16384
_SECSIZE_art = 8

_ADDR__CDROM_Specs_Padding = 22
_SIZE__CDROM_Specs_Padding = 262144
_SECSIZE__CDROM_Specs_Padding = 128

